// AUTO-GENERATED by bs_calib_gen.py — uniform Bloomberg 3M 100%-moneyness IV
// BS model: coupon = beta*BS_mid(S,strike,T,r,iv) + cb*(call-100)/10 - ms*(mb-1)
// beta for RICH4 absorbs Bloomberg IV (recomputed). Anchor stocks: beta=8/BS_mid(anchor).
// Live dashboard computes BS_mid at runtime from live spot -> always fresh.
// T=0.25 (3M), r=0.04 flat. Validated: 22 RICH points max|err|=4.47pt.
const BS_T = 0.25, BS_R = 0.04;
const BLOOMBERG_IV = {"CRDO": 1.1122, "LITE": 0.9968, "AMKR": 0.9849, "COHR": 0.9777, "DRAM": 0.9496, "ARM": 0.9496, "MRVL": 0.9147, "MU": 0.9073, "KLAC": 0.8952, "ASX": 0.8782, "LRCX": 0.8684, "AMAT": 0.8558, "DELL": 0.8532, "INTC": 0.8091, "AMD": 0.7547, "TSM": 0.4917, "NVDA": 0.4274, "SNDK": 1.2053, "AAPL": 0.280194, "1347": 0.9059, "992": 0.6366, "9992": 0.4818, "3690": 0.4483, "1211": 0.4037, "9999": 0.3871, "9618": 0.3616, "9988": 0.4446, "700": 0.3381, "5": 0.2617, "2388": 0.2377, "388": 0.2349, "ALAB": 1.1223, "SKHY": 1.0948, "SOXX": 0.6012};
const CALIB_ANCHOR = {"CRDO": 38, "LITE": 40, "LRCX": 40, "KLAC": 41, "MU": 41, "AMAT": 42, "COHR": 42, "MRVL": 44, "INTC": 44, "ASX": 49, "DELL": 49, "AMD": 51, "992": 64, "9992": 76, "3690": 75, "1211": 80, "9999": 83, "5": 90, "2388": 91.5};
const CALIB_DEFAULT_ANCHOR = {"AMKR": 90, "DRAM": 90, "ARM": 90, "TSM": 90, "NVDA": 90, "1347": 85, "9618": 85, "388": 85, "ALAB": 90, "SKHY": 90, "SOXX": 90};
const RICH_BS = {"AAPL": {"beta": {"0.9074": 5.7286, "0.95": 5.0058}, "cb": {"0.9074": 0.71, "0.95": 0.7}, "ms": 7.27}, "700": {"beta": {"0.881": 5.1803, "0.95": 4.8311}, "cb": {"0.881": 0.08, "0.95": 0.25}, "ms": 7.28}, "SNDK": {"beta": {"0.4": 15.2283, "0.5": 13.415}, "cb": {"0.4": -0.55, "0.5": -1.47}, "ms": 6.61}, "9988": {"beta": {"0.7": 7.5959, "0.95": 4.8032}, "cb": {"0.7": 0.02, "0.95": 0.36}, "ms": 7.37}};
const NO_IV_FALLBACK = [];
if (typeof module!=='undefined') module.exports={BS_T,BS_R,BLOOMBERG_IV,CALIB_ANCHOR,CALIB_DEFAULT_ANCHOR,RICH_BS,NO_IV_FALLBACK};
